
version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - TELEGRAM_BOT_TOKEN=your_telegram_token_here

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
